[package]
name = "ah_app"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.30.5", features = ["rwh_05"] }
bevy_ecs = "0.15.0-rc.3"
tracing-subscriber = "0.3.18"
tracing = "0.1.40"
image = "0.25.5"
